version: '3.0'

services:
  ezpzos-database:
    user: root
    build: 
      context: ../../
      dockerfile: ./docker/DB/Dockerfile
    ports:
        - 1433:1433
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P EZPZOSAdmin! -d EZPZOS -Q "Select 1" || exit 1
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
