# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ebs-serverSQL-pv-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: ebs-sc
#   resources:
#     requests:
#       storage: 4Gi




apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-serversql-pv-claim  # Changed to lowercase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
