apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serversql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: serversql
    spec:
      containers: 
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: SA_PASSWORD
              value: dbpassword11
          ports:
            - containerPort: 1433
              name: sqlserver
          volumeMounts:
            - name: sqlserver-persistent-storage
              mountPath: /var/opt/mssql
            - name: usermanagement-dbcreation-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: sqlserver-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-serversql-pv-claim  # 修正为 ebs-serversql-pv-claim
        - name: usermanagement-dbcreation-script
          configMap:
            name: usermanagement-dbcreation-script  # 保持 ConfigMap 名称正确
