apiVersion: v1
kind: Service
metadata:  # 修改为 metadata
  name: usermgmt-restapp-service
  labels:
    app: usermgmt-restapp  # 缩进修正
spec:
  type: NodePort  # 修正为 type: NodePort
  selector:
    app: usermgmt-restapp  # 确保缩进正确
  ports:
    - port: 8095  # 添加空格，格式修正
      targetPort: 8095  # 添加空格
      nodePort: 31231  # 添加空格
